const clubs = [
  {
    id: "robotics-society",
    name: "Robotics Society",
    focus: "Design, build, and test robots, embedded systems, and automation projects.",
    members: 42,
    contactEmail: "robotics@unihub.ac.ke",
    category: "Technology and Innovation",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "cit",
    departmentName: "School of Computing, Informatics and Technology",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "ai-data-lab",
    name: "AI and Data Lab",
    focus: "Explore machine learning, analytics, and practical data projects for campus and community use.",
    members: 37,
    contactEmail: "aidata@unihub.ac.ke",
    category: "Technology and Research",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "cit",
    departmentName: "School of Computing, Informatics and Technology",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "engineering-design-society",
    name: "Engineering Design Society",
    focus: "Prototype mechanical, electrical, and civil design ideas through student-led build sessions.",
    members: 34,
    contactEmail: "engdesign@unihub.ac.ke",
    category: "Engineering",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "engineering",
    departmentName: "School of Engineering and Built Environment",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "renewable-energy-club",
    name: "Renewable Energy Club",
    focus: "Study solar, wind, and sustainable energy solutions relevant to East African communities.",
    members: 29,
    contactEmail: "energy@unihub.ac.ke",
    category: "Engineering and Sustainability",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "engineering",
    departmentName: "School of Engineering and Built Environment",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "entrepreneurship-finance-society",
    name: "Entrepreneurship and Finance Society",
    focus: "Bring together students interested in startups, business planning, investment, and campus enterprise.",
    members: 46,
    contactEmail: "bizfinance@unihub.ac.ke",
    category: "Business",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "business",
    departmentName: "School of Business and Economics",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "public-health-forum",
    name: "Public Health Forum",
    focus: "Organize health awareness campaigns, peer education, and community wellness outreach.",
    members: 31,
    contactEmail: "healthforum@unihub.ac.ke",
    category: "Health and Outreach",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "health",
    departmentName: "School of Health Sciences",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "agri-innovation-club",
    name: "Agri-Innovation Club",
    focus: "Support smart farming, agribusiness ideas, and sustainable food production projects.",
    members: 27,
    contactEmail: "agriinnovation@unihub.ac.ke",
    category: "Agriculture",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "agriculture",
    departmentName: "School of Agriculture and Environmental Studies",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "debate-policy-forum",
    name: "Debate and Policy Forum",
    focus: "Practice public speaking, policy discussion, and civic dialogue on campus and national issues.",
    members: 39,
    contactEmail: "debateforum@unihub.ac.ke",
    category: "Leadership and Dialogue",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "social-sciences",
    departmentName: "School of Education and Social Sciences",
    approvalStatus: "Approved",
    approved: true,
  },
  {
    id: "undergraduate-research-forum",
    name: "Undergraduate Research Forum",
    focus: "Help students turn class projects into poster sessions, research conversations, and publishable work.",
    members: 25,
    contactEmail: "researchforum@unihub.ac.ke",
    category: "Research and Innovation",
    createdBy: "System Seed",
    createdByEmail: "",
    requestedByEmail: "",
    departmentId: "research-innovation",
    departmentName: "Research and Innovation Directorate",
    approvalStatus: "Approved",
    approved: true,
  },
];

module.exports = clubs;
