const events = [
  {
    id: 1,
    title: "Music Festival",
    date: "2026-05-15",
    month: "May",
    day: "15",
    category: "Performance",
    location: "Student Square",
    time: "6:00 PM",
    description: "A night of student bands, headline performances, and pop-up food stalls.",
    actionLabel: "View Event",
    status: "Open",
  },
  {
    id: 2,
    title: "Tech Workshop",
    date: "2026-05-20",
    month: "May",
    day: "20",
    category: "Workshop",
    location: "Innovation Lab",
    time: "2:00 PM",
    description: "Hands-on coding and product design sessions led by campus mentors.",
    actionLabel: "RSVP",
    status: "Featured",
  },
  {
    id: 3,
    title: "Art Exhibition",
    date: "2026-05-25",
    month: "May",
    day: "25",
    category: "Showcase",
    location: "Fine Arts Hall",
    time: "11:00 AM",
    description: "A curated display of visual work from emerging student artists.",
    actionLabel: "Reserve Spot",
    status: "Limited",
  },
  {
    id: 4,
    title: "Outdoor Movie Night",
    date: "2026-05-22",
    month: "May",
    day: "22",
    category: "Social",
    location: "Central Lawn",
    time: "8:00 PM",
    description: "Bring a blanket and join the film club for a community screening.",
    actionLabel: "Check In",
    status: "Tonight",
  },
];

module.exports = events;
